# Generated by Django 5.2.5 on 2026-01-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
    ]
