# Generated by Django 3.1.1 on 2024-01-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0007_auto_20240107_0002'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alldevices',
            new_name='Alldevice',
        ),
    ]
