# Generated by Django 5.2.5 on 2026-01-19 09:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalimport',
            old_name='hardware',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='import',
            old_name='hardware',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='pendingupdate',
            old_name='hardware',
            new_name='device_name',
        ),
        migrations.AddField(
            model_name='historicalimport',
            name='assignee_cache',
            field=models.CharField(blank=True, editable=False, help_text='Cached full name / staff number for search & reports', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalimport',
            name='uaf_signed',
            field=models.BooleanField(default=False, help_text='Has UAF been signed for this device'),
        ),
        migrations.AddField(
            model_name='import',
            name='assignee_cache',
            field=models.CharField(blank=True, editable=False, help_text='Cached full name / staff number for search & reports', max_length=255),
        ),
        migrations.AddField(
            model_name='import',
            name='uaf_signed',
            field=models.BooleanField(default=False, help_text='Has UAF been signed for this device'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('staff_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(blank=True, help_text="Employee's job title/position", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_user_signature', models.CharField(blank=True, max_length=200)),
                ('issuance_it_signature', models.CharField(blank=True, max_length=200)),
                ('issuance_date', models.DateTimeField(blank=True, null=True)),
                ('user_signed_issuance', models.BooleanField(default=False)),
                ('it_approved_issuance', models.BooleanField(default=False)),
                ('clearance_user_signature', models.CharField(blank=True, max_length=200)),
                ('clearance_it_signature', models.CharField(blank=True, max_length=200)),
                ('clearance_date', models.DateTimeField(blank=True, null=True)),
                ('user_signed_clearance', models.BooleanField(default=False)),
                ('it_approved_clearance', models.BooleanField(default=False)),
                ('clearance_it_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_agreements', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='devices.import')),
                ('issuance_it_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_agreements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_agreements', to='devices.employee')),
            ],
        ),
        migrations.AddField(
            model_name='historicalimport',
            name='assignee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.employee'),
        ),
        migrations.AddField(
            model_name='import',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='devices.employee'),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('staff_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, help_text="Employee's job title/position", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('centre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.centre')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
