# Generated by Django 3.1.1 on 2024-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20240108_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldevice',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alldevice',
            name='uaf_signed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
    ]
