# Generated by Django 5.2.2 on 2025-09-02 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearance',
            name='clearance_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clearance',
            name='cleared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances', to=settings.AUTH_USER_MODEL),
        ),
    ]
