# Generated by Django 5.0.1 on 2024-01-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20240108_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldevice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
