# Generated by Django 5.2.2 on 2025-09-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_department_alter_historicalimport_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('centre_code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalimport',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.department'),
        ),
        migrations.AlterField(
            model_name='import',
            name='department',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department'),
        ),
        migrations.AlterField(
            model_name='pendingupdate',
            name='department',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department'),
        ),
    ]
