# Generated by Django 5.2.2 on 2025-09-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_department_alter_historicalimport_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='centre_code',
            new_name='department_code',
        ),
    ]
