# Generated by Django 5.2.5 on 2026-01-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20260119_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceagreement',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='clearance_it_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='clearance_user_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='issuance_it_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='issuance_user_signature',
            field=models.TextField(blank=True),
        ),
    ]
