# Generated by Django 5.2.2 on 2025-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_centre_code_department_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimport',
            name='disposal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalimport',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='import',
            name='disposal_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='is_disposed',
            field=models.BooleanField(default=False),
        ),
    ]
