# Generated by Django 5.2.5 on 2026-01-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_deviceagreement_is_archived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceagreement',
            old_name='clearance_it_signature',
            new_name='clearance_it_signature_png',
        ),
        migrations.RenameField(
            model_name='deviceagreement',
            old_name='clearance_user_signature',
            new_name='clearance_user_signature_png',
        ),
        migrations.RenameField(
            model_name='deviceagreement',
            old_name='issuance_it_signature',
            new_name='issuance_it_signature_png',
        ),
        migrations.RenameField(
            model_name='deviceagreement',
            old_name='issuance_user_signature',
            new_name='issuance_user_signature_png',
        ),
    ]
