# Generated by Django 5.2.5 on 2026-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_rename_clearance_it_signature_deviceagreement_clearance_it_signature_png_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceagreement',
            options={'ordering': ['-issuance_date']},
        ),
        migrations.AddField(
            model_name='deviceagreement',
            name='clearance_remarks',
            field=models.TextField(blank=True, help_text='Optional remarks about device condition on return'),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='clearance_it_signature_png',
            field=models.TextField(blank=True, help_text="IT staff's drawn signature for clearance"),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='clearance_user_signature_png',
            field=models.TextField(blank=True, help_text="Employee's drawn signature for clearance"),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='issuance_it_signature_png',
            field=models.TextField(blank=True, help_text="IT staff's drawn signature for issuance"),
        ),
        migrations.AlterField(
            model_name='deviceagreement',
            name='issuance_user_signature_png',
            field=models.TextField(blank=True, help_text="Employee's drawn signature for issuance"),
        ),
    ]
