# Generated by Django 3.1.1 on 2024-01-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20240116_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Importdevice',
            new_name='Import',
        ),
    ]
