# Generated by Django 5.2.2 on 2025-09-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_historicalimport_disposal_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.department'),
        ),
        migrations.AlterField(
            model_name='import',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department'),
        ),
    ]
