# Generated by Django 5.2.6 on 2025-09-19 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_historicalimport_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pendingupdate',
            name='pending_clarification',
            field=models.BooleanField(default=False),
        ),
    ]
