# Generated by Django 5.2.5 on 2026-02-20 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_devicelog'),
        ('ppm', '0002_ppmtaskattempt_alter_ppmperiod_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='ppm_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppm.ppmtaskattempt'),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='ppm_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppm.ppmtask'),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
