# Generated by Django 5.2.6 on 2025-09-22 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_notification_responded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assignee_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assignee_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('cleared_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='devices.import')),
            ],
        ),
    ]
