# Generated by Django 3.1.1 on 2024-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20240119_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='assignee_email_address',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='assignee_first_name',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='assignee_last_name',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='device_condition',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='hdd_gb',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='ram_gb',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='system_model',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='csv_file',
            field=models.FileField(null=True, upload_to='uploaded_csv_files/'),
        ),
    ]
