# Generated by Django 5.2.5 on 2025-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_deviceuserhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_it_manager',
            field=models.BooleanField(default=False, help_text='IT Manager - receives notifications for staff work plans'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_senior_it_officer',
            field=models.BooleanField(default=False, help_text='Senior IT Officer - receives notifications for trainer work plans'),
        ),
    ]
