# Generated by Django 5.2.5 on 2026-02-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_devicelog_ppm_attempt_devicelog_ppm_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='ppm_attempt',
        ),
    ]
