# Generated by Django 3.1.1 on 2024-01-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20240119_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('hardware', models.CharField(max_length=500)),
                ('system_model', models.CharField(max_length=500)),
                ('device_name', models.CharField(max_length=500)),
                ('processor', models.CharField(max_length=500)),
                ('ram_gb', models.CharField(max_length=500)),
                ('hdd_gb', models.CharField(max_length=500)),
                ('serial_number', models.CharField(max_length=500)),
                ('assigned_by', models.CharField(max_length=500)),
                ('assignee_first_name', models.CharField(max_length=500)),
                ('assignee_last_name', models.CharField(max_length=500)),
                ('assignee_email_address', models.CharField(max_length=500)),
                ('device_condition', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='CSVData',
        ),
    ]
