# Generated by Codex on 2026-03-03

from django.conf import settings
from django.db import migrations
from django.utils import timezone


def _build_message(*, no_activity: bool, activities: list[str], reason: str, notes: str) -> str:
    prefix = "PPM"
    if no_activity:
        msg = f"{prefix}: NO activity performed."
        if reason:
            msg += f"\nReason: {reason}"
        if notes:
            msg += f"\nNotes: {notes}"
        return msg

    msg = f"{prefix}: Activities performed: " + (", ".join(activities) if activities else "N/A")
    if notes:
        msg += f"\nNotes: {notes}"
    return msg


def backfill_ppm_devicelogs(apps, schema_editor):
    DeviceLog = apps.get_model("devices", "DeviceLog")
    PPMTask = apps.get_model("ppm", "PPMTask")

    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)

    fallback_user = User.objects.filter(is_superuser=True).order_by("id").first()
    if fallback_user is None:
        fallback_user = User.objects.order_by("id").first()
    if fallback_user is None:
        return

    existing_task_ids = set(
        DeviceLog.objects.exclude(ppm_task_id=None).values_list("ppm_task_id", flat=True)
    )

    qs = (
        PPMTask.objects.select_related("device", "period", "created_by")
        .prefetch_related("activities")
        .order_by("id")
    )

    new_logs = []
    for task in qs:
        if task.id in existing_task_ids:
            continue

        device = getattr(task, "device", None)
        if device is None:
            continue

        user = getattr(task, "created_by", None) or fallback_user

        no_activity = bool(getattr(task, "no_ppm_activity_performed", False))
        reason = (getattr(task, "reason", "") or "").strip()

        notes_val = ""
        if hasattr(task, "remarks"):
            notes_val = task.remarks or ""
        elif hasattr(task, "notes"):
            notes_val = task.notes or ""
        notes_val = (notes_val or "").strip()

        activities = []
        if not no_activity and hasattr(task, "activities"):
            activities = list(task.activities.all().values_list("name", flat=True))

        msg = _build_message(
            no_activity=no_activity,
            activities=activities,
            reason=reason,
            notes=notes_val,
        )

        created_at = (
            getattr(task, "updated_at", None)
            or getattr(task, "created_at", None)
            or timezone.now()
        )

        new_logs.append(
            DeviceLog(
                device=device,
                user=user,
                message=msg,
                created_at=created_at,
                ppm_task=task,
            )
        )

    if new_logs:
        DeviceLog.objects.bulk_create(new_logs, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0012_device_configuration"),
        ("ppm", "0004_ppmtask_no_ppm_activity_performed"),
    ]

    operations = [
        migrations.RunPython(backfill_ppm_devicelogs, migrations.RunPython.noop),
    ]

