# Generated by Codex on 2026-03-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0013_backfill_ppm_devicelogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If false, the device is inactive (e.g., under repair) and actions are blocked.",
            ),
        ),
        migrations.CreateModel(
            name="DeviceRepair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_repair", models.DateField(blank=True, null=True)),
                ("centre_department", models.CharField(blank=True, max_length=255, null=True)),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("serial_number", models.CharField(blank=True, max_length=100, null=True)),
                ("reported_by", models.CharField(blank=True, max_length=255, null=True)),
                ("issue_description", models.TextField()),
                ("repair_action_taken", models.TextField(blank=True, null=True)),
                ("technician_responsible", models.CharField(blank=True, max_length=255, null=True)),
                ("cost_kes", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed"), ("written_off", "Written off")],
                        default="in_progress",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("external_repair", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repairs_created",
                        to="devices.customuser",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repairs", to="devices.import"),
                ),
            ],
            options={"ordering": ["-date_of_repair", "-created_at"]},
        ),
    ]

