# Generated by Django 3.1.1 on 2024-01-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_auto_20240119_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
