# Generated by Codex on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0014_import_is_active_and_devicerepair"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalimport",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If false, the device is inactive (e.g., under repair) and actions are blocked.",
            ),
        ),
    ]

