# Generated by Django 3.1.1 on 2024-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_auto_20240120_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
