# Generated by Codex on 2026-03-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0017_customuser_staff_signature_png"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingupdate",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("laptop", "Laptop"),
                    ("system_unit", "System Unit"),
                    ("monitor", "Monitor"),
                    ("tv", "Television"),
                    ("networking_devices", "Networking Devices"),
                    ("printer", "Printer"),
                    ("n_computing", "N Computing"),
                    ("projector", "projector"),
                    ("gadget", "Gadget"),
                    ("access_point", "Access Point"),
                    ("power_backup_equipment", "Power & Backup Equipment"),
                    ("other", "Other"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pendingupdate",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_device_updates",
                to="devices.employee",
            ),
        ),
    ]

