# Generated by Django 3.1.1 on 2024-01-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_auto_20240120_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
