# Generated by Django 3.1.1 on 2024-01-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_importreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Importreport',
        ),
    ]
