# Generated by Codex on 2026-03-10

from __future__ import annotations

import re
from collections import defaultdict

from django.db import migrations, models


def _classify_gadget_text(text: str) -> str:
    """
    Returns one of: smart_phone, desk_phone, ipad, tablet.
    Fallback requirement: if we can't confidently match, return ipad.
    """
    text = (text or "").lower()

    ipad_keywords = [
        "ipad",
        "i-pad",
        "i pad",
        "ipads",
        "ipad pro",
        "ipad air",
        "ipad mini",
        "apple ipad",
    ]
    if any(k in text for k in ipad_keywords):
        return "ipad"

    desk_phone_keywords = [
        "desk phone",
        "ip phone",
        "ipphone",
        "pbx phone",
        "pbx",
        "sip phone",
        "sip",
        "voip",
        "yealink",
        "grandstream",
        "avaya",
        "polycom",
        "mitel",
        "fanvil",
        "nec",
        "cisco phone",
    ]
    if any(k in text for k in desk_phone_keywords) or re.search(r"\b(ip|sip|voip|pbx)\s*phone\b", text):
        return "desk_phone"

    tablet_keywords = [
        "tablet",
        "galaxy tab",
        "matepad",
        "lenovo tab",
        "amazon fire",
        "fire hd",
        "kindle",
        "surface go",
    ]
    if any(k in text for k in tablet_keywords) or re.search(r"\btab\s*[a-z0-9\-]*\b", text):
        return "tablet"

    smart_phone_keywords = [
        "smartphone",
        "smart phone",
        "mobile phone",
        "cell phone",
        "android",
        "iphone",
        "phone",
        "tecno",
        "infinix",
        "samsung",
        "galaxy",
        "nokia",
        "huawei",
        "oppo",
        "vivo",
        "xiaomi",
        "redmi",
        "pixel",
        "oneplus",
        "sony",
        "motorola",
        "moto",
        "itel",
    ]
    if any(k in text for k in smart_phone_keywords):
        return "smart_phone"

    return "ipad"


def _combined_text(row: dict) -> str:
    parts = [
        row.get("device_name") or "",
        row.get("system_model") or "",
        row.get("processor") or "",
        row.get("serial_number") or "",
    ]
    return " ".join(p for p in parts if p).strip()


def forwards_split_gadgets(apps, schema_editor):
    Import = apps.get_model("devices", "Import")
    PendingUpdate = apps.get_model("devices", "PendingUpdate")

    def _recat(model, qs):
        ids_by_new_category = defaultdict(list)
        for row in qs:
            text = _combined_text(row)
            new_category = _classify_gadget_text(text)
            ids_by_new_category[new_category].append(row["id"])

        for new_category, ids in ids_by_new_category.items():
            model.objects.filter(id__in=ids).update(category=new_category)

    # Split existing "gadget" devices into the new broader buckets.
    _recat(
        Import,
        Import.objects.filter(category="gadget").values(
            "id",
            "device_name",
            "system_model",
            "processor",
            "serial_number",
        ),
    )

    # Keep pending updates consistent (if any exist in the legacy "gadget" category).
    _recat(
        PendingUpdate,
        PendingUpdate.objects.filter(category="gadget").values(
            "id",
            "device_name",
            "system_model",
            "processor",
            "serial_number",
        ),
    )


def reverse_noop(apps, schema_editor):
    # Data migration is not safely reversible.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0018_pendingupdate_category_and_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="category",
            field=models.CharField(
                choices=[
                    ("laptop", "Laptop"),
                    ("system_unit", "System Unit"),
                    ("monitor", "Monitor"),
                    ("tv", "Television"),
                    ("networking_devices", "Networking Devices"),
                    ("printer", "Printer"),
                    ("n_computing", "N Computing"),
                    ("projector", "projector"),
                    ("smart_phone", "Smart Phones"),
                    ("desk_phone", "Desk Phones"),
                    ("ipad", "iPads"),
                    ("tablet", "Tablets"),
                    ("access_point", "Access Point"),
                    ("power_backup_equipment", "Power & Backup Equipment"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Device category/type",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="pendingupdate",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("laptop", "Laptop"),
                    ("system_unit", "System Unit"),
                    ("monitor", "Monitor"),
                    ("tv", "Television"),
                    ("networking_devices", "Networking Devices"),
                    ("printer", "Printer"),
                    ("n_computing", "N Computing"),
                    ("projector", "projector"),
                    ("smart_phone", "Smart Phones"),
                    ("desk_phone", "Desk Phones"),
                    ("ipad", "iPads"),
                    ("tablet", "Tablets"),
                    ("access_point", "Access Point"),
                    ("power_backup_equipment", "Power & Backup Equipment"),
                    ("other", "Other"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_split_gadgets, reverse_noop),
    ]

