# Generated by Codex on 2026-03-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0019_split_gadget_into_phone_tablet_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicerepair",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Current IT officer responsible for continuing this repair.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repairs_assigned",
                to="devices.customuser",
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE devices_devicerepair
                SET assigned_to_id = created_by_id
                WHERE assigned_to_id IS NULL AND created_by_id IS NOT NULL
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
