# Generated by Django 5.2.5 on 2026-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_devicerepair_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('system_unit', 'System Unit'), ('monitor', 'Monitor'), ('tv', 'Television'), ('networking_devices', 'Networking Devices'), ('printer', 'Printer'), ('n_computing', 'N Computing'), ('projector', 'projector'), ('smart_phone', 'Smart Phones'), ('desk_phone', 'Desk Phones'), ('ipad', 'iPads'), ('tablet', 'Tablets'), ('access_point', 'Access Point'), ('power_backup_equipment', 'Power & Backup Equipment'), ('other', 'Other')], default='other', help_text='Device category/type', max_length=200),
        ),
    ]
