# Generated by Django 3.2.23 on 2024-01-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20240123_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='department',
        ),
    ]
