# Generated by Django 3.2.23 on 2024-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_import_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('centre', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('device', models.CharField(blank=True, max_length=500, null=True)),
                ('system_model', models.CharField(blank=True, max_length=500, null=True)),
                ('processor', models.CharField(blank=True, max_length=500, null=True)),
                ('ram_gb', models.CharField(blank=True, max_length=500, null=True)),
                ('hdd_gb', models.CharField(blank=True, max_length=500, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=500, null=True)),
                ('assignee_first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('assignee_last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('assignee_email_address', models.CharField(blank=True, max_length=500, null=True)),
                ('device_condition', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Import',
        ),
    ]
