# Generated by Django 3.2.23 on 2024-03-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_auto_20240305_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device'),
        ),
    ]
