# Generated by Django 3.2.23 on 2024-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_alter_item_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='device_name_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
