# Generated by Django 3.2.23 on 2024-03-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_item_device_name_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='device_name_temp',
            new_name='device_type',
        ),
    ]
