# Generated by Django 5.1.5 on 2025-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_rename_device_name_temp_item_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='device',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
