# Generated by Django 5.1.5 on 2025-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_item_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('centre', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=500, null=True)),
                ('hardware', models.CharField(blank=True, max_length=500, null=True)),
                ('system_model', models.CharField(blank=True, max_length=500, null=True)),
                ('device_name', models.CharField(blank=True, max_length=500, null=True)),
                ('processor', models.CharField(blank=True, max_length=500, null=True)),
                ('ram_gb', models.CharField(blank=True, max_length=500, null=True)),
                ('hdd_gb', models.CharField(blank=True, max_length=500, null=True)),
                ('cpu_serial_number', models.CharField(blank=True, max_length=500, null=True)),
                ('monitor_serial_number', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=500, null=True)),
                ('assignee_first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('assignee_last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('assignee_email_address', models.CharField(blank=True, max_length=500, null=True)),
                ('device_condition', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
