# Generated by Django 5.1.5 on 2025-01-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_import_delete_device_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import',
            old_name='assigned_by',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='import',
            name='cpu_serial_number',
        ),
        migrations.RemoveField(
            model_name='import',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='import',
            name='monitor_serial_number',
        ),
    ]
