# Generated by Django 5.2.2 on 2025-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_rename_assigned_by_import_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('centre_code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='import',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
