# Generated by Django 5.2.2 on 2025-08-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_centre_alter_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre'),
        ),
    ]
