# Generated by Django 5.2.2 on 2025-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_alter_import_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='centre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
