# Generated by Django 5.2.2 on 2025-08-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_import_is_approved_import_reason_for_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre'),
        ),
    ]
