# Generated by Django 5.2.2 on 2025-08-15 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_imports', to=settings.AUTH_USER_MODEL),
        ),
    ]
