# Generated by Django 5.2.2 on 2025-08-19 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_alter_import_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='file',
        ),
        migrations.AlterField(
            model_name='import',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='import',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='import',
            name='assignee_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='assignee_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='assignee_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='device_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='hardware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='hdd_gb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='ram_gb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='system_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PendingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware', models.CharField(blank=True, max_length=100, null=True)),
                ('system_model', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_gb', models.CharField(blank=True, max_length=10, null=True)),
                ('hdd_gb', models.CharField(blank=True, max_length=10, null=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('assignee_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assignee_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assignee_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('device_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason_for_update', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre')),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='devices.import')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
