# Generated by Django 5.2.2 on 2025-08-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0042_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
