# Generated by Django 5.2.2 on 2025-08-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_alter_historicalimport_date_alter_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimport',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
