"""
Django settings for itinventory project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
import pymysql

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#DB NAME FOR TEST TEMPLATE CONFIXIGURATION
DB_NAME_CONFIG=os.getenv('DB_NAME')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=7ap+(zql*g##=bjqpdk9sgtd76k%ayih&k&qz(2y(t0^!7u^x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if DEBUG:
    ALLOWED_HOSTS = []
else:
    if DB_NAME_CONFIG == 'ufdxwals_it_test_db':
        ALLOWED_HOSTS = ['test.mohiit.org', 'www.test.mohiit.org', 'pld109.truehost.cloud']
    else:
        ALLOWED_HOSTS = ['mohiit.org', 'www.mohiit.org', 'pld109.truehost.cloud']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'devices',
    'ppm',
    'it_operations',
    'simple_history',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
   
]

ROOT_URLCONF = 'itinventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ictinventory', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'devices.context_processors.notification_count',
                'devices.context_processors.global_settings',
            ],

        },
    },
]


WSGI_APPLICATION = 'itinventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



pymysql.install_as_MySQLdb()
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_test.sqlite3',
        }
}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES';",
            },
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# media
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

AUTH_USER_MODEL = 'devices.CustomUser'
LOGOUT_REDIRECT_URL = 'login'

LOGIN_URL = 'login'  
# Optional but recommended:
LOGIN_REDIRECT_URL = 'dashboard'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True
# ============================================================================
# ⭐ SESSION SECURITY CONFIGURATION (2 HOURS AUTO-LOGOUT)
# ============================================================================

SESSION_COOKIE_AGE = 7200  

# Session expires when browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Save session on every request (updates last activity time)
SESSION_SAVE_EVERY_REQUEST = True

# Use database-backed sessions (more secure and allows cleanup)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session cookie settings for security
SESSION_COOKIE_SECURE = True  # Only send cookie over HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_NAME = 'mohi_sessionid'  # Custom session cookie name

# ============================================================================
# ⭐ CACHE CONFIGURATION (DISABLE CACHING FOR FRESH CONTENT)
# ============================================================================

# Disable browser caching - forces users to get fresh content after deployment
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

# Cache middleware seconds (0 = no caching)
CACHE_MIDDLEWARE_SECONDS = 0

# ============================================================================
# ⭐ BROWSER CACHE CONTROL HEADERS
# ============================================================================

# Prevent browser from caching pages
# These headers will be added by the middleware
CACHE_CONTROL_MAX_AGE = 0
CACHE_CONTROL_NO_CACHE = True
CACHE_CONTROL_NO_STORE = True
CACHE_CONTROL_MUST_REVALIDATE = True

# ============================================================================
# EXISTING SECURITY SETTINGS
# ============================================================================

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True

# ============================================================================
# ⭐ ADDITIONAL SECURITY HEADERS
# ============================================================================

# Prevent caching of sensitive pages
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Additional security settings
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True



# ============================================================================
# ⭐ DEVELOPMENT-ONLY SECURITY RELAXATION
# ============================================================================

if DEBUG:
    # Allow session cookies over HTTP during development
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # Disable automatic redirect to HTTPS in development
    SECURE_SSL_REDIRECT = False

    # Optional: Allow CSRF over HTTP (useful if testing forms locally)
    # CSRF_COOKIE_HTTPONLY = False  # Usually not needed, but available if required

    # Relax HSTS in development (prevents browser from forcing HTTPS)
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

    # Allow iframe embedding during development (useful for testing)
    X_FRAME_OPTIONS = 'ALLOWALL'  # or 'SAMEORIGIN' if you prefer slightly safer

else:
    pass


# ============================================================================
# Email CONFIGURATION
# ============================================================================
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = 465
    EMAIL_USE_SSL = True
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

#BACKUP PASSWORD
DB_BACKUP_ENCRYPTION_PASSWORD = os.getenv('BACKUP_PASSWORD')

# ============================================================================
# SITE URL CONFIGURATION
if DEBUG:
    SITE_URL = 'http://127.0.0.1:8000'
else:
    if DATABASES['default']['NAME'] == 'ufdxwals_it_test_db':
        SITE_URL = os.getenv('SITE_URL_TEST', 'http://127.0.0.1:8000')
    else:
        SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')
# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  
    
    # Define the format of the log message
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    
    # Define where the logs will go (e.g., a file)
    'handlers': {
        'error_file': {
            'level': 'ERROR',  # Log only ERROR and CRITICAL messages
            'class': 'logging.FileHandler',
            # This is the crucial part:
            'filename': os.path.join(BASE_DIR, 'logs/errors.log'),
            'formatter': 'verbose', # Use the 'verbose' formatter defined above
        },
        'debug_file': {
            'level': 'DEBUG', # Log EVERYTHING from DEBUG level up
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
            'formatter': 'simple',
        },
    },
    
    # Define which loggers to use
    'loggers': {
        'django': {
            'handlers': ['error_file'], # Send 'django' logger messages to 'error_file'
            'level': 'ERROR',          # Only process ERROR messages
            'propagate': True,
        },
       
    },
}






