# Generated by Django 5.2.5 on 2026-01-14 09:23

import django.db.models.deletion
import it_operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('quickbooks', 'QuickBooks'), ('smartcare', 'SmartCare'), ('inventory', 'Inventory Systems')], help_text='System/Software being backed up', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_registries', to='devices.centre')),
                ('done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Registry',
                'verbose_name_plural': 'Backup Registries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_title_role', models.CharField(help_text='Title / Role of the person reporting', max_length=255)),
                ('incident_number', models.CharField(default=it_operations.models.get_next_incident_number, max_length=50, unique=True)),
                ('date_of_report', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Open', max_length=50)),
                ('incident_type', models.CharField(help_text='e.g., INTERNET OUTAGE, SERVER DOWN', max_length=255)),
                ('date_of_incident', models.DateTimeField(blank=True, help_text='Date and time the incident occurred', null=True)),
                ('location', models.CharField(help_text="e.g., BUSTANI (CEO'S RESIDENCE)", max_length=255)),
                ('specific_area', models.CharField(blank=True, help_text='Specific area (if applicable)', max_length=255, null=True)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('parties_involved', models.TextField(blank=True, help_text='Name / Role / Contact / Statement of parties involved', null=True)),
                ('witnesses', models.TextField(blank=True, help_text='Name / Role / Contact of witnesses', null=True)),
                ('immediate_actions_taken', models.TextField(blank=True, help_text='Immediate actions taken', null=True)),
                ('reported_to', models.CharField(blank=True, help_text='Name/Role of person(s) the incident was reported to', max_length=255, null=True)),
                ('follow_up_actions_required', models.TextField(blank=True, help_text='Any follow-up actions required', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes or recommendations', null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='incident_collaborations', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-date_of_incident'],
            },
        ),
        migrations.CreateModel(
            name='MissionCriticalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/Description of the asset', max_length=255)),
                ('category', models.CharField(choices=[('Application', 'Application'), ('Infrastructure', 'Infrastructure'), ('Network', 'Network'), ('Security', 'Security'), ('Storage', 'Storage'), ('Backup', 'Backup'), ('Power', 'Power'), ('Cooling', 'Cooling'), ('Other', 'Other')], max_length=50)),
                ('location_scope', models.CharField(blank=True, help_text='Location/Scope (e.g., HQ & Data Centers)', max_length=255, null=True)),
                ('purpose_function', models.TextField(help_text='Purpose/Function of the asset')),
                ('dependency_linked_system', models.TextField(blank=True, help_text='Dependency/Linked System', null=True)),
                ('backup_recovery_method', models.TextField(help_text='Backup/Recovery Method')),
                ('criticality_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_critical_assets_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_critical_assets', to='devices.department')),
            ],
            options={
                'verbose_name': 'Mission Critical Asset',
                'verbose_name_plural': 'Mission Critical Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='The Monday date of this work week')),
                ('week_end_date', models.DateField(help_text='The Saturday date of this work week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Plan',
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkPlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Specific calendar date for this task')),
                ('is_leave', models.BooleanField(default=False, help_text='Is the staff member on leave this day?')),
                ('task_name', models.CharField(help_text='What is the specific task?', max_length=255)),
                ('other_parties', models.TextField(blank=True, help_text='External vendors, non-IT staff, or other stakeholders involved', null=True)),
                ('resources_needed', models.TextField(blank=True, help_text='Hardware, Software, Transport, Budget, etc.', null=True)),
                ('target', models.CharField(blank=True, help_text="Measurable outcome (e.g., '50 PCs serviced')", max_length=500, null=True)),
                ('comments', models.TextField(blank=True, help_text='User remarks or justification', null=True)),
                ('reschedule_reason', models.TextField(blank=True, help_text='Reason for rescheduling this task (required when rescheduling)', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Not Done', 'Not Done')], default='Pending', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre')),
                ('collaborators', models.ManyToManyField(blank=True, help_text='Internal IT Staff or Trainers working on this specific task', related_name='collaborating_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='it_operations.workplan')),
            ],
            options={
                'verbose_name': 'Work Plan Task',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
