# Generated by Django 5.2.5 on 2025-10-29 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupregistry',
            name='system',
            field=models.CharField(choices=[('quickbooks', 'QuickBooks'), ('smartcare', 'SmartCare'), ('inventory', 'Inventory Systems')], help_text='System/Software being backed up', max_length=50),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='week_end_date',
            field=models.DateField(help_text='Saturday of the week (Sunday excluded)'),
        ),
        migrations.CreateModel(
            name='WorkPlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('task_description', models.TextField(help_text='Description of the task')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='it_operations.workplan')),
            ],
            options={
                'verbose_name': 'Work Plan Task',
                'verbose_name_plural': 'Work Plan Tasks',
                'ordering': ['day', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlanTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='it_operations.workplantask')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
