# Generated by Django 5.2.5 on 2025-11-03 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_customuser_is_it_manager_and_more'),
        ('it_operations', '0002_alter_backupregistry_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplantask',
            name='task_description',
        ),
        migrations.AddField(
            model_name='workplantask',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre/Location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.centre'),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments/details about the task', null=True),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.department'),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='human_resources',
            field=models.ManyToManyField(blank=True, help_text='Assigned staff members', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='items_needed',
            field=models.CharField(blank=True, help_text='Items/resources needed (e.g., Portal, Help desk)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='target',
            field=models.CharField(blank=True, help_text='Target/Desired outcome', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workplantask',
            name='task_name',
            field=models.CharField(default='Untitled Task', help_text='Task name/title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplantask',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed'), ('Not Done', 'Not Done')], default='Not Done', max_length=20),
        ),
        migrations.AlterField(
            model_name='workplantaskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='it_operations.workplantask'),
        ),
    ]
