# Generated by Django 5.2.5 on 2025-11-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("it_operations", "0003_remove_workplantask_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missioncriticalasset",
            name="location_scope",
            field=models.CharField(
                blank=True,
                help_text="Location/Scope (e.g., HQ & Data Centers)",
                max_length=255,
                null=True,
            ),
        ),
    ]
