# Generated by Django 5.2.5 on 2025-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("it_operations", "0004_alter_missioncriticalasset_location_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missioncriticalasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("Application", "Application"),
                    ("Infrastructure", "Infrastructure"),
                    ("Network", "Network"),
                    ("Security", "Security"),
                    ("Storage", "Storage"),
                    ("Backup", "Backup"),
                    ("Power", "Power"),
                    ("Cooling", "Cooling"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
