# Generated by Django 5.2.5 on 2025-11-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0004_alter_missioncriticalasset_category_and_more'),
        ('it_operations', '0005_alter_missioncriticalasset_category'),
    ]

    operations = [
    ]
