# Generated by Django 5.2.5 on 2025-11-05 10:01

import django.db.models.deletion
import it_operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0006_merge_20251105_1301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_title_role', models.CharField(help_text='Title / Role of the person reporting', max_length=255)),
                ('incident_number', models.CharField(default=it_operations.models.get_next_incident_number, max_length=50, unique=True)),
                ('date_of_report', models.DateTimeField(auto_now_add=True)),
                ('incident_type', models.CharField(help_text='e.g., INTERNET OUTAGE, SERVER DOWN', max_length=255)),
                ('date_of_incident', models.DateTimeField(help_text='Date and time the incident occurred')),
                ('location', models.CharField(help_text="e.g., BUSTANI (CEO'S RESIDENCE)", max_length=255)),
                ('specific_area', models.CharField(blank=True, help_text='Specific area (if applicable)', max_length=255, null=True)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('parties_involved', models.TextField(blank=True, help_text='Name / Role / Contact / Statement of parties involved', null=True)),
                ('witnesses', models.TextField(blank=True, help_text='Name / Role / Contact of witnesses', null=True)),
                ('immediate_actions_taken', models.TextField(blank=True, help_text='Immediate actions taken', null=True)),
                ('reported_to', models.CharField(blank=True, help_text='Name/Role of person(s) the incident was reported to', max_length=255, null=True)),
                ('follow_up_actions_required', models.TextField(blank=True, help_text='Any follow-up actions required', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes or recommendations', null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='incident_collaborations', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-date_of_incident'],
            },
        ),
    ]
