# Generated by Django 5.2.5 on 2025-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_operations', '0007_incidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='date_of_incident',
            field=models.DateTimeField(blank=True, help_text='Date and time the incident occurred', null=True),
        ),
    ]
