# Generated by Django 5.2.5 on 2026-02-20 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_devicelog'),
        ('ppm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPMTaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('no_ppm_activity_performed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AlterField(
            model_name='ppmperiod',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='periods', to='ppm.ppmactivity'),
        ),
        migrations.AlterField(
            model_name='ppmtask',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='tasks_planned', to='ppm.ppmactivity'),
        ),
        migrations.AlterField(
            model_name='ppmtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppm_tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ppmtask',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ppm.ppmperiod'),
        ),
        migrations.AddConstraint(
            model_name='ppmtask',
            constraint=models.UniqueConstraint(fields=('device', 'period'), name='uniq_ppm_task_device_period'),
        ),
        migrations.AddField(
            model_name='ppmtaskattempt',
            name='performed_activities',
            field=models.ManyToManyField(blank=True, related_name='attempts', to='ppm.ppmactivity'),
        ),
        migrations.AddField(
            model_name='ppmtaskattempt',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppm_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ppmtaskattempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ppm.ppmtask'),
        ),
    ]
