# Generated by Django 5.2.5 on 2026-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_remove_devicelog_ppm_attempt'),
        ('ppm', '0002_ppmtaskattempt_alter_ppmperiod_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppmtask',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='ppm.ppmactivity'),
        ),
        migrations.DeleteModel(
            name='PPMTaskAttempt',
        ),
    ]
