# Generated by Django 5.2.5 on 2026-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppm', '0003_alter_ppmtask_activities_delete_ppmtaskattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmtask',
            name='no_ppm_activity_performed',
            field=models.BooleanField(default=False),
        ),
    ]
