# Generated by Django 5.2.2 on 2025-08-29 11:50

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('PC', 'PC'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Printer', 'Printer'), ('UPS', 'UPS')], max_length=100)),
                ('device_name', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=500)),
                ('assigned_by', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=100)),
                ('centre', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('activities', multiselectfield.db.fields.MultiSelectField(choices=[('Complete static dust extraction', 'Complete static dust extraction'), ('Internal Cleaning', 'Internal Cleaning'), ('Clean and inspect power supply', 'Clean and inspect power supply'), ('Cable ties and arrangement', 'Cable ties and arrangement'), ('Inspect for loose screws and corrosion', 'Inspect for loose screws and corrosion'), ('Detailed external cleaning', 'Detailed external cleaning'), ('System test and verification', 'System test and verification'), ('Check for software loaded in the PC', 'Check for software loaded in the PC'), ('Load the latest antivirus on the PC', 'Load the latest antivirus on the PC'), ('Clean and lubricate moving parts/gears', 'Clean and lubricate moving parts/gears'), ('Test printer, working properly', 'Test printer, working properly'), ('Returned', 'Returned')], max_length=1000)),
                ('issues', models.CharField(max_length=1000)),
                ('recommendations', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
