# Generated by Django 5.0.1 on 2024-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
