# Generated by Django 5.0.1 on 2024-01-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0002_alter_device_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='centre_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itstaff',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mohiuser',
            name='staff_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
