# Generated by Django 5.0.1 on 2024-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0003_alter_centre_centre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Not Issued', 'Not Issued'), ('Returned', 'Returned')], max_length=50),
        ),
    ]
