# Generated by Django 5.0.1 on 2024-01-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0004_alter_device_device_condition_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
