# Generated by Django 3.1.1 on 2024-01-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0009_auto_20240116_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='it_staff',
            new_name='assigned_by',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='assignee',
        ),
    ]
