# Generated by Django 3.1.1 on 2024-01-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_report'),
        ('ictinventory', '0013_auto_20240121_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'department'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.import'),
        ),
    ]
