# Generated by Django 3.1.1 on 2024-01-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0015_auto_20240121_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ictinventory.department'),
        ),
    ]
