# Generated by Django 3.1.1 on 2024-01-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ictinventory', '0017_auto_20240121_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ictinventory.department'),
        ),
    ]
